name: KEA Monitor

on:
  schedule:
    - cron: "*/10 * * * *"

  workflow_dispatch:

jobs:
  monitor:

    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Monitor
        run: |
          python app.py